/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.13
 * Generated at: 2023-10-13 14:42:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class UpdateBooking_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1696178473678L));
    _jspx_dependants.put("jar:file:/F:/RouteMaster/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/RouterMaster/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602854172000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>RouteMaste</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        @font-face {\r\n");
      out.write("        font-family: 'Roboto-Light'; /* Font family name */\r\n");
      out.write("        src: url('Fonts/Roboto-Light.ttf') format('truetype'); /* URL to your font file */\r\n");
      out.write("        font-weight: normal;\r\n");
      out.write("        font-style: italic;\r\n");
      out.write("        }\r\n");
      out.write("        @font-face {\r\n");
      out.write("        font-family: 'Raleway-Light'; /* Font family name */\r\n");
      out.write("        src: url('Fonts/Raleway-Light.ttf') format('truetype'); /* URL to your font file */\r\n");
      out.write("        font-weight: normal;\r\n");
      out.write("        font-style: italic;\r\n");
      out.write("        }\r\n");
      out.write("        @font-face {\r\n");
      out.write("        font-family: 'Roboto-Bold'; /* Font family name */\r\n");
      out.write("        src: url('Fonts/Roboto-Bold.ttf') format('truetype'); /* URL to your font file */\r\n");
      out.write("        font-weight: normal;\r\n");
      out.write("        font-style: italic;\r\n");
      out.write("        }\r\n");
      out.write("        :root{\r\n");
      out.write("            --div-color1:#000000;\r\n");
      out.write("            --div-color2:#272702;\r\n");
      out.write("            --div-color3:#07FAFA;\r\n");
      out.write("            --div-color4:#FFFFFF;	\r\n");
      out.write("        }\r\n");
      out.write("        a{\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("        body{\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            background-image: url(background.jpg);\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("            background-position: center;\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        body::before {\r\n");
      out.write("          content: \"\";\r\n");
      out.write("          position: absolute;\r\n");
      out.write("          top: 0;\r\n");
      out.write("          left: 0;\r\n");
      out.write("          width: 100%;\r\n");
      out.write("          height: 100%;\r\n");
      out.write("          background-color: rgba(245, 236, 236, 0.5); \r\n");
      out.write("          z-index: -1;\r\n");
      out.write("        }\r\n");
      out.write("        .head{\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: row;\r\n");
      out.write("            justify-content: right;\r\n");
      out.write("        }\r\n");
      out.write("        header h3{\r\n");
      out.write("            color: var(--div-color1);\r\n");
      out.write("            font-size:1rem;\r\n");
      out.write("            margin-right: 3rem;\r\n");
      out.write("            cursor: grab;\r\n");
      out.write("            padding: 0.5rem;\r\n");
      out.write("            border-radius: 0.5rem;\r\n");
      out.write("            outline: none;\r\n");
      out.write("            font-family: 'Roboto-Light'; \r\n");
      out.write("        }\r\n");
      out.write("        span{\r\n");
      out.write("            width: 3rem;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding-top: 1rem;\r\n");
      out.write("            padding-bottom: 1rem;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            background-color:rgb(16, 129, 41);\r\n");
      out.write("            outline: none;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            font-family: 'Roboto-Light'; \r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        .side1{\r\n");
      out.write("            width: 30%;\r\n");
      out.write("            height: 70vh;\r\n");
      out.write("        }\r\n");
      out.write("        .side2{\r\n");
      out.write("            width: 30%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        .row1,.row2,.row3,.row4{\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: row;\r\n");
      out.write("            justify-content: space-around;\r\n");
      out.write("            margin-bottom: 12vh;\r\n");
      out.write("        }\r\n");
      out.write("        .column1,.column2{\r\n");
      out.write("            width: 40%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: row;\r\n");
      out.write("            justify-content: space-around;\r\n");
      out.write("        }\r\n");
      out.write("        main{\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: row;\r\n");
      out.write("            justify-content: space-around;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        button{\r\n");
      out.write("          text-align: center;\r\n");
      out.write("          padding-left: 2rem;\r\n");
      out.write("          padding-right: 2rem;\r\n");
      out.write("          padding-top: 0.8rem;\r\n");
      out.write("          padding-bottom: 0.8rem;\r\n");
      out.write("          border-radius: 10px;\r\n");
      out.write("          font-family: 'Roboto-Bold'; \r\n");
      out.write("          background-color: var(--div-color1);\r\n");
      out.write("          color: var(--div-color4);\r\n");
      out.write("          border: none;\r\n");
      out.write("          outline: none;\r\n");
      out.write("          cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        .details1,.details2{\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: row;\r\n");
      out.write("            \r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        h1{\r\n");
      out.write("          font-size: 2.5rem;\r\n");
      out.write("          text-align: center;\r\n");
      out.write("          margin-top: 3rem;\r\n");
      out.write("        }\r\n");
      out.write("        h2{\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("          font-family: 'Raleway-Light'; \r\n");
      out.write("        }\r\n");
      out.write("        #seats{\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("          font-family: 'Raleway-Light'; \r\n");
      out.write("            margin-left: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("        #total{\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("          font-family: 'Raleway-Light'; \r\n");
      out.write("            margin-left: 1rem;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        .column10{\r\n");
      out.write("          	width: 40%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: row;\r\n");
      out.write("            justify-content: space-around;\r\n");
      out.write("        }\r\n");
      out.write("        </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    \r\n");
      out.write("     <header>\r\n");
      out.write("        <div class=\"head\">\r\n");
      out.write("          <a href=\"Home.jsp\"><h3 id=\"m1\">Home</h3></a>\r\n");
      out.write("           <a href=\"AboutUs.jsp\"><h3 id=\"m2\">About</h3></a>\r\n");
      out.write("            <a href=\"ContactUS.jsp\"><h3 id=\"m3\">Contact</h3></a>\r\n");
      out.write("           <a href=\"login.jsp\"><h3 id=\"m4\">LogOut</h3></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <main>\r\n");
      out.write("        <div class=\"side1\">\r\n");
      out.write("            <div class=\"row1\">\r\n");
      out.write("                <div class=\"column1\">\r\n");
      out.write("                    <span id=\"s1\">1</span>\r\n");
      out.write("                    <span id=\"s2\">2</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            <div class=\"column2\">\r\n");
      out.write("                <span id=\"s3\">3</span>\r\n");
      out.write("                <span id=\"s4\">4</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row2\">\r\n");
      out.write("            <div class=\"column1\">\r\n");
      out.write("                <span id=\"s5\">5</span>\r\n");
      out.write("                <span id=\"s6\">6</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        <div class=\"column2\">\r\n");
      out.write("            <span id=\"s7\">7</span>\r\n");
      out.write("            <span id=\"s8\">8</span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"row3\">\r\n");
      out.write("        <div class=\"column1\">\r\n");
      out.write("            <span id=\"s9\">9</span>\r\n");
      out.write("            <span id=\"s10\">10</span>\r\n");
      out.write("        </div>\r\n");
      out.write("    <div class=\"column2\">\r\n");
      out.write("        <span id=\"s11\">11</span>\r\n");
      out.write("        <span id=\"s12\">12</span>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row4\">\r\n");
      out.write("    <div class=\"column1\">\r\n");
      out.write("        <span id=\"s13\">13</span>\r\n");
      out.write("        <span id=\"s14\">14</span>\r\n");
      out.write("    </div>\r\n");
      out.write("<div class=\"column2\">\r\n");
      out.write("    <span id=\"s15\">15</span>\r\n");
      out.write("    <span id=\"s16\">16</span>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"side2\">\r\n");
      out.write("            <form action=\"BookingServlet\" method=\"Get\">\r\n");
      out.write(" <h1>Seat Details</h1>\r\n");
      out.write(" \r\n");
      out.write(" ");

 
 String RID=request.getParameter("RID");
 String FID=request.getParameter("FID");
 String place=request.getParameter("place");
 String venue=request.getParameter("venue");
 String date=request.getParameter("date");
 String seats=request.getParameter("seats");
 String payment=request.getParameter("payment");

 
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" <div class=\"column10\">\r\n");
      out.write(" <h2>RID</h2>\r\n");
      out.write(" <input type=\"text\" name=\"RID\" value=\"");
      out.print(RID);
      out.write("\" readonly>\r\n");
      out.write(" </div>\r\n");
      out.write(" <div class=\"column10\">\r\n");
      out.write(" <h2>FID</h2>\r\n");
      out.write("  <input type=\"text\" name=\"FID\" value=\"");
      out.print(FID);
      out.write("\" readonly>\r\n");
      out.write(" </div>\r\n");
      out.write(" <div class=\"column10\">\r\n");
      out.write(" <h2>Place</h2>\r\n");
      out.write("  <input type=\"text\" name=\"place\" value=\"");
      out.print(place);
      out.write("\" readonly>\r\n");
      out.write(" </div>\r\n");
      out.write(" <div class=\"column10\">\r\n");
      out.write(" <h2>Venue</h2>\r\n");
      out.write("   <input type=\"text\" name=\"Venue\" value=\"");
      out.print(RID);
      out.write("\" readonly>\r\n");
      out.write(" </div>\r\n");
      out.write("  <div class=\"column10\">\r\n");
      out.write(" <h2>Date</h2>\r\n");
      out.write("   <input type=\"text\" name=\"date\" value=\"");
      out.print(date);
      out.write("\" readonly>\r\n");
      out.write(" </div>\r\n");
      out.write("  <div class=\"column10\">\r\n");
      out.write(" <h2>Seats</h2>\r\n");
      out.write("   <input type=\"text\" name=\"seats\" value=\"");
      out.print(seats);
      out.write("\">\r\n");
      out.write(" </div>\r\n");
      out.write("  <div class=\"column10\">\r\n");
      out.write(" <h2>Payment</h2>\r\n");
      out.write("   <input type=\"text\" name=\"payment\" value=\"");
      out.print(payment);
      out.write("\">\r\n");
      out.write(" </div>\r\n");
      out.write("  	\r\n");
      out.write("		<p id=\"seat\" name=\"seat\"></p>\r\n");
      out.write("		<p id=\"tota\" name=\"tota\"></p>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"details1\">\r\n");
      out.write("        <h2>Seats</h2>\r\n");
      out.write("        <label id=\"sea\" name=\"seat\">0</label>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"details2\">\r\n");
      out.write("        <h2>Total</h2>\r\n");
      out.write("        <label id=\"total\" name=\"total\">0</label>\r\n");
      out.write("    </div>\r\n");
      out.write("    <button id=\"btn\">Continue to pay</button>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" </div>\r\n");
      out.write("                \r\n");
      out.write("            </form>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </main>    \r\n");
      out.write("    <script>\r\n");
      out.write("\r\n");
      out.write("        var M1=document.getElementById(\"m1\");\r\n");
      out.write("        var M2=document.getElementById(\"m2\");\r\n");
      out.write("        var M3=document.getElementById(\"m3\");\r\n");
      out.write("        var M4=document.getElementById(\"m4\");\r\n");
      out.write("        var BTN=document.getElementById(\"btn\");\r\n");
      out.write("        var S1=document.getElementById(\"s1\");\r\n");
      out.write("        var S2=document.getElementById(\"s2\");\r\n");
      out.write("        var S3=document.getElementById(\"s3\");\r\n");
      out.write("        var S4=document.getElementById(\"s4\");\r\n");
      out.write("        var S5=document.getElementById(\"s5\");\r\n");
      out.write("        var S6=document.getElementById(\"s6\");\r\n");
      out.write("        var S7=document.getElementById(\"s7\");\r\n");
      out.write("        var S8=document.getElementById(\"s8\");\r\n");
      out.write("        var S9=document.getElementById(\"s9\");\r\n");
      out.write("        var S10=document.getElementById(\"s10\");\r\n");
      out.write("        var S11=document.getElementById(\"s11\");\r\n");
      out.write("        var S12=document.getElementById(\"s12\");\r\n");
      out.write("        var S13=document.getElementById(\"s13\");\r\n");
      out.write("        var S14=document.getElementById(\"s14\");\r\n");
      out.write("        var S15=document.getElementById(\"s15\");\r\n");
      out.write("        var S16=document.getElementById(\"s16\");\r\n");
      out.write("        var Seats=document.getElementById(\"sea\");\r\n");
      out.write("        var Total=document.getElementById(\"total\");\r\n");
      out.write("        function updateSeatsLabel() {\r\n");
      out.write("            var seatsLabel = document.getElementById(\"seats\");\r\n");
      out.write("            var Total1=document.getElementById(\"totals\");\r\n");
      out.write("            if (seatsLabel) {\r\n");
      out.write("                seatsLabel.value = count;\r\n");
      out.write("                Total1.value=count*450;\r\n");
      out.write("               \r\n");
      out.write("            }\r\n");
      out.write("        }      \r\n");
      out.write("    \r\n");
      out.write("        M1.onmousemove=function(){\r\n");
      out.write("          M1.style.backgroundColor=\"var(--div-color3)\";\r\n");
      out.write("          M1.style.color=\"var(--div-color4)\";\r\n");
      out.write("        }\r\n");
      out.write("        M1.onmouseout=function(){\r\n");
      out.write("          M1.style.backgroundColor=\"\";\r\n");
      out.write("          M1.style.color=\"var(--div-color1)\";\r\n");
      out.write("        }\r\n");
      out.write("        M2.onmousemove=function(){\r\n");
      out.write("          M2.style.backgroundColor=\"var(--div-color3)\";\r\n");
      out.write("          M2.style.color=\"var(--div-color4)\";\r\n");
      out.write("        }\r\n");
      out.write("        M2.onmouseout=function(){\r\n");
      out.write("          M2.style.backgroundColor=\"\";\r\n");
      out.write("          M2.style.color=\"var(--div-color1)\";\r\n");
      out.write("        }\r\n");
      out.write("        M3.onmousemove=function(){\r\n");
      out.write("          M3.style.backgroundColor=\"var(--div-color3)\";\r\n");
      out.write("          M3.style.color=\"var(--div-color4)\";\r\n");
      out.write("        }\r\n");
      out.write("        M3.onmouseout=function(){\r\n");
      out.write("          M3.style.backgroundColor=\"\";\r\n");
      out.write("          M3.style.color=\"var(--div-color1)\";\r\n");
      out.write("        }\r\n");
      out.write("        M4.onmousemove=function(){\r\n");
      out.write("          M4.style.backgroundColor=\"var(--div-color3)\";\r\n");
      out.write("          M4.style.color=\"var(--div-color4)\";\r\n");
      out.write("        }\r\n");
      out.write("        M4.onmouseout=function(){\r\n");
      out.write("          M4.style.backgroundColor=\"\";\r\n");
      out.write("          M4.style.color=\"var(--div-color1)\";\r\n");
      out.write("        }\r\n");
      out.write("        /* Above javascript code must include all tha page.don't change the code.*/\r\n");
      out.write("        BTN.onmousemove=function(){\r\n");
      out.write("          BTN.style.color=\"var(--div-color1)\";\r\n");
      out.write("          BTN.style.backgroundColor=\"var(--div-color4)\";\r\n");
      out.write("        }\r\n");
      out.write("        BTN.onmouseout=function(){\r\n");
      out.write("          BTN.style.color=\"var(--div-color4)\";\r\n");
      out.write("          BTN.style.backgroundColor=\"var(--div-color1)\";\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        var s1=1;\r\n");
      out.write("        var count=0;\r\n");
      out.write("        S1.onclick=function(){\r\n");
      out.write("            if(s1==1){\r\n");
      out.write("                S1.style.backgroundColor=\"red\";\r\n");
      out.write("                ++s1;\r\n");
      out.write("                ++count;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                Total.innerHTML=count*450\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("\r\n");
      out.write("            }else if(s1==2){\r\n");
      out.write("                --s1;\r\n");
      out.write("                --count;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                S1.style.backgroundColor=\"rgb(16, 129, 41)\"\r\n");
      out.write("                    updateSeatsLabel(); // Update the label\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        var s2=1;\r\n");
      out.write("        S2.onclick=function(){\r\n");
      out.write("            if(s2==1){\r\n");
      out.write("                S2.style.backgroundColor=\"red\";\r\n");
      out.write("                ++s2;\r\n");
      out.write("                ++count;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("\r\n");
      out.write("            }else if(s2==2){\r\n");
      out.write("                --s2;\r\n");
      out.write("                --count;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                S2.style.backgroundColor=\"rgb(16, 129, 41)\";\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        var s3=1;\r\n");
      out.write("        S3.onclick=function(){\r\n");
      out.write("            if(s3==1){\r\n");
      out.write("                S3.style.backgroundColor=\"red\";\r\n");
      out.write("                ++s3;\r\n");
      out.write("                ++count;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("\r\n");
      out.write("            }else if(s3==2){\r\n");
      out.write("                --s3;\r\n");
      out.write("                --count;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                S3.style.backgroundColor=\"rgb(16, 129, 41)\";\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        var s4=1;\r\n");
      out.write("        S4.onclick=function(){\r\n");
      out.write("            if(s4==1){\r\n");
      out.write("                S4.style.backgroundColor=\"red\";\r\n");
      out.write("                ++s4;\r\n");
      out.write("                ++count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                Seats.innerHTML=count\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            }else if(s4==2){\r\n");
      out.write("                --s4;\r\n");
      out.write("                --count;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                S4.style.backgroundColor=\"rgb(16, 129, 41)\";\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        var s5=1;\r\n");
      out.write("        S5.onclick=function(){\r\n");
      out.write("            if(s5==1){\r\n");
      out.write("                S5.style.backgroundColor=\"red\";\r\n");
      out.write("                ++s5;\r\n");
      out.write("                ++count;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("            }else if(s5==2){\r\n");
      out.write("                --s5;\r\n");
      out.write("                --count;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                S5.style.backgroundColor=\"rgb(16, 129, 41)\";\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        var s6=1;\r\n");
      out.write("        S6.onclick=function(){\r\n");
      out.write("            if(s6==1){\r\n");
      out.write("                S6.style.backgroundColor=\"red\";\r\n");
      out.write("                ++s6;\r\n");
      out.write("                ++count;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("\r\n");
      out.write("            }else if(s6==2){\r\n");
      out.write("                --s6;\r\n");
      out.write("                --count;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                S6.style.backgroundColor=\"rgb(16, 129, 41)\";\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        var s7=1;\r\n");
      out.write("        S7.onclick=function(){\r\n");
      out.write("            if(s7==1){\r\n");
      out.write("                S7.style.backgroundColor=\"red\";\r\n");
      out.write("                ++s7;\r\n");
      out.write("                ++count;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("            }else if(s7==2){\r\n");
      out.write("                --s7;\r\n");
      out.write("                --count;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                S7.style.backgroundColor=\"rgb(16, 129, 41)\";\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        var s8=1;\r\n");
      out.write("        S8.onclick=function(){\r\n");
      out.write("            if(s8==1){\r\n");
      out.write("                S8.style.backgroundColor=\"red\";\r\n");
      out.write("                ++s8;\r\n");
      out.write("                ++count;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("            }else if(s8==2){\r\n");
      out.write("                --s8;\r\n");
      out.write("                --count;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                S8.style.backgroundColor=\"rgb(16, 129, 41)\";\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        var s9=1;\r\n");
      out.write("        S9.onclick=function(){\r\n");
      out.write("            if(s9==1){\r\n");
      out.write("                S9.style.backgroundColor=\"red\";\r\n");
      out.write("                ++s9;\r\n");
      out.write("                ++count;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("\r\n");
      out.write("            }else if(s9==2){\r\n");
      out.write("                --s9;\r\n");
      out.write("                --count;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                S9.style.backgroundColor=\"rgb(16, 129, 41)\";\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        var s10=1;\r\n");
      out.write("        S10.onclick=function(){\r\n");
      out.write("            if(s10==1){\r\n");
      out.write("                S10.style.backgroundColor=\"red\";\r\n");
      out.write("                ++s10;\r\n");
      out.write("                ++count;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("            }else if(s10==2){\r\n");
      out.write("                --s10;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                S10.style.backgroundColor=\"rgb(16, 129, 41)\";\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        var s11=1;\r\n");
      out.write("        S11.onclick=function(){\r\n");
      out.write("            if(s11==1){\r\n");
      out.write("                S11.style.backgroundColor=\"red\";\r\n");
      out.write("                ++s11;\r\n");
      out.write("                ++count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("\r\n");
      out.write("            }else if(s11==2){\r\n");
      out.write("                --s11;\r\n");
      out.write("                --count;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                S11.style.backgroundColor=\"rgb(16, 129, 41)\";\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        var s12=1;\r\n");
      out.write("        S12.onclick=function(){\r\n");
      out.write("            if(s12==1){\r\n");
      out.write("                S12.style.backgroundColor=\"red\";\r\n");
      out.write("                ++s12;\r\n");
      out.write("                ++count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("\r\n");
      out.write("            }else if(s12==2){\r\n");
      out.write("                --s12;\r\n");
      out.write("                --count;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                S12.style.backgroundColor=\"rgb(16, 129, 41)\";\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        var s13=1;\r\n");
      out.write("        S13.onclick=function(){\r\n");
      out.write("            if(s13==1){\r\n");
      out.write("                S13.style.backgroundColor=\"red\";\r\n");
      out.write("                ++s13;\r\n");
      out.write("                ++count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("            }else if(s13==2){\r\n");
      out.write("                --s13;\r\n");
      out.write("                --count;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                S13.style.backgroundColor=\"rgb(16, 129, 41)\";\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        var s14=1;\r\n");
      out.write("        S14.onclick=function(){\r\n");
      out.write("            if(s14==1){\r\n");
      out.write("                S14.style.backgroundColor=\"red\";\r\n");
      out.write("                ++s14;\r\n");
      out.write("                ++count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("\r\n");
      out.write("            }else if(s14==2){\r\n");
      out.write("                --s14;\r\n");
      out.write("                --count;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                S14.style.backgroundColor=\"rgb(16, 129, 41)\";\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        var s15=1;\r\n");
      out.write("        S15.onclick=function(){\r\n");
      out.write("            if(s15==1){\r\n");
      out.write("                S15.style.backgroundColor=\"red\";\r\n");
      out.write("                ++s15;\r\n");
      out.write("                ++count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("\r\n");
      out.write("            }else if(s15==2){\r\n");
      out.write("                --s15;\r\n");
      out.write("                --count;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                S15.style.backgroundColor=\"rgb(16, 129, 41)\";\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        var s16=1;\r\n");
      out.write("        S16.onclick=function(){\r\n");
      out.write("            if(s16==1){\r\n");
      out.write("                S16.style.backgroundColor=\"red\";\r\n");
      out.write("                ++s16;\r\n");
      out.write("                ++count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("\r\n");
      out.write("            }else if(s16==2){\r\n");
      out.write("                --s16;\r\n");
      out.write("                --count;\r\n");
      out.write("                Seats.innerHTML=count;\r\n");
      out.write("                Total.innerHTML=count*450;\r\n");
      out.write("                S16.style.backgroundColor=\"rgb(16, 129, 41)\";\r\n");
      out.write("                updateSeatsLabel(); // Update the label\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("      \r\n");
      out.write("        updateSeatsLabel();\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("       </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
